# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1TrU9eNzLn1FQvgyajbnLjJ5SE3vDat
"""

import streamlit as st
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import json
from pathlib import Path

# --- 1. DEFINICIÓN DE LA ARQUITECTURA DEL MODELO ---
# La arquitectura del modelo es correcta y no necesita cambios.
class RiskNN(nn.Module):
    def __init__(self, num_features, cat_dims, emb_dims, hidden, dropout):
        super().__init__()
        self.emb = nn.ModuleList([
            nn.Embedding(dim, emb) for dim, emb in zip(cat_dims, emb_dims)
        ])

        layer_list = []
        current_dim = num_features + sum(emb_dims)

        for hidden_size in hidden:
            layer_list.append(nn.Linear(current_dim, hidden_size))
            layer_list.append(nn.BatchNorm1d(hidden_size))
            layer_list.append(nn.GELU())
            layer_list.append(nn.Dropout(dropout))
            current_dim = hidden_size

        layer_list.append(nn.Linear(current_dim, 1))
        self.net = nn.Sequential(*layer_list)

    def forward(self, x_num, x_cat):
        emb = [m(x_cat[:, i]) for i, m in enumerate(self.emb)]
        x = torch.cat(emb + [x_num], dim=1)
        return self.net(x).squeeze(1)

# --- 2. FUNCIÓN PARA CARGAR EL MODELO (EN CACHÉ) ---
@st.cache_resource
def load_model_and_artifacts():
    """Carga el modelo, metadatos y estadísticas de normalización."""
    base_path = Path(__file__).parent
    model_dir = base_path / "modeloFinal"

    with open(model_dir / "model_metadata.json", 'r') as f:
        metadata = json.load(f)

    model = RiskNN(
        num_features=metadata['num_features'],
        cat_dims=metadata['cat_dims'],
        emb_dims=metadata['emb_dims'],
        hidden=metadata['hidden_layers'],
        dropout=metadata['dropout'],
    )

    model.load_state_dict(torch.load(model_dir / "best_model_final.pth", map_location=torch.device("cpu"), weights_only=True))
    model.eval()

    norm_stats = {
        'means': pd.Series({
            'loan_amnt': 14755.26, 'annual_inc': 75035.56, 'dti': 18.14, 'revol_util': 55.0,
            'total_acc': 25.41, 'tot_cur_bal': 139474.49, 'days_since_earliest_cr': 5851.05
        }),
        'stds': pd.Series({
            'loan_amnt': 8435.46, 'annual_inc': 64149.29, 'dti': 8.37, 'revol_util': 24.5,
            'total_acc': 11.84, 'tot_cur_bal': 153749.12, 'days_since_earliest_cr': 2724.08
        })
    }

    return model, metadata, norm_stats

# --- 3. CONFIGURACIÓN DE LA PÁGINA ---
st.set_page_config(page_title="Evaluador de Riesgo Crediticio NN", page_icon="🤖", layout="centered")
st.title("🤖 Evaluador de Riesgo Crediticio ")
st.markdown("Ingrese los datos del solicitante para obtener una predicción de riesgo.")
st.markdown("---")

# --- 4. CARGAR MODELO ---
try:
    nn_model, metadata, norm_stats = load_model_and_artifacts()
    st.success("Modelo de Red Neuronal cargado exitosamente.")
except Exception as e:
    st.error(f"Error al cargar el modelo: {e}")
    st.stop()

# --- 5. FORMULARIO DE ENTRADA (CON OPCIONES ORIGINALES) ---
with st.form("formulario_riesgo_nn"):
    st.subheader("📋 Datos del Solicitante")

    col1, col2 = st.columns(2)
    with col1:
        loan_amnt = st.number_input("💰 Monto del Préstamo ($)", min_value=1000.0, value=15000.0, step=500.0)
        annual_inc = st.number_input("📈 Ingreso Anual ($)", min_value=10000.0, value=75000.0, step=1000.0)
        dti = st.number_input("📊 Ratio Deuda/Ingreso (DTI)", min_value=0.0, value=18.0, step=0.1)
        revol_util = st.number_input("📉 Uso de Crédito Revolvente (%)", min_value=0.0, max_value=100.0, value=55.0, step=0.1)

    with col2:
        total_acc = st.number_input("📂 Cuentas de Crédito Totales", min_value=0, value=25)
        tot_cur_bal = st.number_input("💼 Saldo Corriente Total ($)", min_value=0.0, value=140000.0, step=1000.0)
        days_since_earliest_cr = st.number_input("⏳ Antigüedad Crediticia (días)", min_value=365, value=5800)

    st.markdown("---")

    # Opciones que ve el usuario (ANTES de la transformación de EDA)
    emp_length_options = ['< 1 year', '1 year', '2 years', '3 years', '4 years', '5 years', '6 years', '7 years', '8 years', '9 years', '10+ years']
    home_ownership_options = ['RENT', 'OWN', 'MORTGAGE', 'OTHER', 'ANY', 'NONE']
    purpose_options = [
        'debt_consolidation', 'credit_card', 'home_improvement', 'other', 'major_purchase', 'car',
        'house', 'vacation', 'wedding', 'moving', 'medical', 'educational', 'small_business', 'renewable_energy'
    ]
    delinq_2yrs_options = ['0', '1', '>=2']
    inq_last_6mths_options = ['0', '1', '>=2'] # Esta no se transforma en la EDA
    pub_rec_options = ['0', '1', '>=2']

    col3, col4 = st.columns(2)
    with col3:
        emp_length = st.selectbox("📆 Antigüedad Laboral", options=emp_length_options, index=10)
        home_ownership = st.selectbox("🏠 Tipo de Vivienda", options=home_ownership_options, index=2)
        purpose = st.selectbox("🎯 Propósito del Préstamo", options=purpose_options, index=0)

    with col4:
        delinq_2yrs = st.selectbox("❌ Morosidades (últimos 2 años)", options=delinq_2yrs_options, index=0)
        inq_last_6mths = st.selectbox("📌 Solicitudes de Crédito (últimos 6 meses)", options=inq_last_6mths_options, index=1)
        pub_rec = st.selectbox("⚖️ Registros Públicos Negativos", options=pub_rec_options, index=0)

    enviado = st.form_submit_button("Evaluar Riesgo")

# --- 6. PROCESAMIENTO Y PREDICCIÓN (CON LÓGICA DE EDA) ---
if enviado:
    # ***** INICIO DE LA CORRECCIÓN: APLICAR TRANSFORMACIONES DE EDA *****

    # 1. Transformar las entradas del usuario según las reglas del notebook

    # -- emp_length --
    if emp_length in ['5 years', '6 years', '7 years', '8 years', '9 years', '10+ years']:
        processed_emp_length = '5+ years'
    else:
        processed_emp_length = emp_length

    # -- home_ownership --
    if home_ownership in ['ANY', 'NONE']:
        processed_home_ownership = 'OTHER'
    else:
        processed_home_ownership = home_ownership

    # -- purpose --
    purpose_mapping_eda = {
        'debt_consolidation': 'debt_consolidation', 'credit_card': 'credit_related', 'major_purchase': 'credit_related',
        'car': 'credit_related', 'home_improvement': 'credit_related', 'house': 'credit_related', 'vacation': 'personal_expenses',
        'wedding': 'personal_expenses', 'moving': 'personal_expenses', 'medical': 'personal_expenses',
        'educational': 'personal_expenses', 'small_business': 'small_business', 'renewable_energy': 'other', 'other': 'other'
    }
    processed_purpose = purpose_mapping_eda.get(purpose, 'other')

    # -- delinq_2yrs --
    if delinq_2yrs in ['1', '>=2']:
        processed_delinq_2yrs = '>=1'
    else:
        processed_delinq_2yrs = '0'

    # -- pub_rec --
    if pub_rec in ['1', '>=2']:
        processed_pub_rec = '>=1'
    else:
        processed_pub_rec = '0'

    # -- inq_last_6mths no cambia --
    processed_inq_last_6mths = inq_last_6mths

    # 2. Crear los mapeos a índices basados en las categorías FINALES (post-EDA), ordenadas alfabéticamente.
    final_cat_options = {
        'emp_length': sorted(['< 1 year', '1 year', '2 years', '3 years', '4 years', '5+ years']),
        'home_ownership': sorted(['RENT', 'OWN', 'MORTGAGE', 'OTHER']),
        'purpose': sorted(list(set(purpose_mapping_eda.values()))), # Obtener categorías únicas
        'delinq_2yrs': sorted(['0', '>=1']),
        'inq_last_6mths': sorted(['0', '1', '>=2']), # Opciones originales
        'pub_rec': sorted(['0', '>=1'])
    }

    final_cat_maps = {
        key: {val: i for i, val in enumerate(options)}
        for key, options in final_cat_options.items()
    }

    # 3. Convertir las variables procesadas a sus índices numéricos
    try:
        cat_inputs = [
            final_cat_maps['emp_length'][processed_emp_length],
            final_cat_maps['home_ownership'][processed_home_ownership],
            final_cat_maps['purpose'][processed_purpose],
            final_cat_maps['delinq_2yrs'][processed_delinq_2yrs],
            final_cat_maps['inq_last_6mths'][processed_inq_last_6mths],
            final_cat_maps['pub_rec'][processed_pub_rec]
        ]
        tensor_cat = torch.tensor([cat_inputs], dtype=torch.long)
    except KeyError as e:
        st.error(f"Error de mapeo final: la categoría procesada '{e.args[0]}' no se encontró. Revisa la lógica de EDA.")
        st.stop()

    # ***** FIN DE LA CORRECCIÓN *****

    # Procesamiento de Variables Numéricas (se mantiene igual)
    num_inputs_df = pd.DataFrame([[
        loan_amnt, annual_inc, dti, revol_util, total_acc, tot_cur_bal, days_since_earliest_cr
    ]], columns=list(norm_stats['means'].index))

    num_inputs_normalized = (num_inputs_df - norm_stats['means']) / norm_stats['stds']
    num_inputs_final = np.insert(num_inputs_normalized.values, 0, 0, axis=1)
    tensor_num = torch.tensor(num_inputs_final, dtype=torch.float32)

    # Realizar la Predicción
    with torch.no_grad():
        logits = nn_model(tensor_num, tensor_cat)
        probability = torch.sigmoid(logits).item()

    # Mostrar el Resultado
    st.markdown("---")
    prob_percent = probability * 100

    st.subheader("Resultado de la Evaluación")
    if probability > 0.5:
        st.error(f"🔴 Riesgo Alto (Probabilidad de Incumplimiento: {prob_percent:.2f}%)")
        st.warning("Recomendación: Es probable que el crédito sea rechazado.")
    else:
        st.success(f"🟢 Riesgo Bajo (Probabilidad de Incumplimiento: {prob_percent:.2f}%)")
        st.info("Recomendación: Es probable que el crédito sea aprobado.")
        st.balloons()

    st.progress(probability)

    with st.expander("Ver detalles técnicos de la predicción"):
        st.write(f"**Logit del modelo (salida cruda):** `{logits.item():.4f}`")
        st.write(f"**Probabilidad (Sigmoid):** `{probability:.4f}`")
        st.write("**Valores categóricos procesados (Post-EDA):**")
        st.json({
            "Antigüedad Laboral": processed_emp_length,
            "Tipo de Vivienda": processed_home_ownership,
            "Propósito": processed_purpose,
            "Morosidades": processed_delinq_2yrs,
            "Solicitudes": processed_inq_last_6mths,
            "Registros Públicos": processed_pub_rec
        })
        st.write("**Tensor de entrada categórico (índices):**")
        st.write(tensor_cat)